In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.legend import Legend
import matplotlib.patches as mpatches
import seaborn as sns
#from statsmodels.graphics.mosaicplot import mosaic
import io
import requests

%matplotlib inline


#import xgboost as xgb
#from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn import tree

from sklearn.metrics import log_loss

In [3]:
entrenamiento_df = pd.read_csv('dataset_v3')

In [4]:
test_df = pd.read_csv('encoded_test_values.csv')

In [5]:
entrenamiento_df.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,count_families,damage_grade,roof_type_C1,roof_type_C0,...,has_superstructure_cement_mortar_stone_mean,has_superstructure_mud_mortar_brick_mean,has_superstructure_cement_mortar_brick_mean,has_superstructure_timber_mean,has_superstructure_bamboo_mean,has_superstructure_rc_non_engineered_mean,has_superstructure_rc_engineered_mean,has_superstructure_other_mean,area_percentage_norm,height_percentage_norm
0,802906,6,487,12198,2,30,1,3,0,1,...,0.981765,0.931846,0.924732,0.745012,0.914989,0.95741,0.984141,0.985015,0.050505,0.100000
1,28830,8,900,2812,2,10,1,2,0,1,...,0.981765,0.931846,0.924732,0.745012,0.914989,0.95741,0.984141,0.985015,0.070707,0.166667
2,94947,21,363,8973,2,10,1,3,0,1,...,0.981765,0.931846,0.924732,0.745012,0.914989,0.95741,0.984141,0.985015,0.040404,0.100000
3,590882,22,418,10694,2,10,1,2,0,1,...,0.981765,0.931846,0.924732,0.254988,0.085011,0.95741,0.984141,0.985015,0.050505,0.100000
4,201944,11,131,1488,3,30,1,3,0,1,...,0.981765,0.931846,0.924732,0.745012,0.914989,0.95741,0.984141,0.985015,0.070707,0.233333