In [1]:
import datetime as datetime
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train_values.csv')
df.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,...,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,...,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 39 columns):
building_id                               260601 non-null int64
geo_level_1_id                            260601 non-null int64
geo_level_2_id                            260601 non-null int64
geo_level_3_id                            260601 non-null int64
count_floors_pre_eq                       260601 non-null int64
age                                       260601 non-null int64
area_percentage                           260601 non-null int64
height_percentage                         260601 non-null int64
land_surface_condition                    260601 non-null object
foundation_type                           260601 non-null object
roof_type                                 260601 non-null object
ground_floor_type                         260601 non-null object
other_floor_type                          260601 non-null object
position                                  260601 non-null object
plan_configuration                        260601 non-null object
has_superstructure_adobe_mud              260601 non-null int64
has_superstructure_mud_mortar_stone       260601 non-null int64
has_superstructure_stone_flag             260601 non-null int64
has_superstructure_cement_mortar_stone    260601 non-null int64
has_superstructure_mud_mortar_brick       260601 non-null int64
has_superstructure_cement_mortar_brick    260601 non-null int64
has_superstructure_timber                 260601 non-null int64
has_superstructure_bamboo                 260601 non-null int64
has_superstructure_rc_non_engineered      260601 non-null int64
has_superstructure_rc_engineered          260601 non-null int64
has_superstructure_other                  260601 non-null int64
legal_ownership_status                    260601 non-null object
count_families                            260601 non-null int64
has_secondary_use                         260601 non-null int64
has_secondary_use_agriculture             260601 non-null int64
has_secondary_use_hotel                   260601 non-null int64
has_secondary_use_rental                  260601 non-null int64
has_secondary_use_institution             260601 non-null int64
has_secondary_use_school                  260601 non-null int64
has_secondary_use_industry                260601 non-null int64
has_secondary_use_health_post             260601 non-null int64
has_secondary_use_gov_office              260601 non-null int64
has_secondary_use_use_police              260601 non-null int64
has_secondary_use_other                   260601 non-null int64
dtypes: int64(31), object(8)
memory usage: 77.5+ MB

In [7]:
df2 = pd.read_csv('train_labels.csv')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 2 columns):
building_id     260601 non-null int64
damage_grade    260601 non-null int64
dtypes: int64(2)
memory usage: 4.0 MB

In [6]:
df['land_surface_condition'] = df['land_surface_condition'].astype('category')
df['legal_ownership_status'] = df['legal_ownership_status'].astype('category')
df['land_surface_condition'] = df['land_surface_condition'].astype('category')
df['foundation_type'] = df['foundation_type'].astype('category')
df['roof_type'] = df['roof_type'].astype('category')
df['ground_floor_type'] = df['ground_floor_type'].astype('category')
df['other_floor_type'] = df['other_floor_type'].astype('category')
df['position'] = df['position'].astype('category')
df['plan_configuration'] = df['plan_configuration'].astype('category')

In [10]:
df['has_secondary_use'] = df['has_secondary_use'].astype('bool')
df['has_secondary_use_agriculture'] = df['has_secondary_use_agriculture'].astype('bool')
df['has_secondary_use_hotel'] = df['has_secondary_use_hotel'].astype('bool')
df['has_secondary_use_rental'] = df['has_secondary_use_rental'].astype('bool')
df['has_secondary_use_institution'] = df['has_secondary_use_institution'].astype('bool')
df['has_secondary_use_school'] = df['has_secondary_use_school'].astype('bool')
df['has_secondary_use_industry'] = df['has_secondary_use_industry'].astype('bool')
df['has_secondary_use_health_post'] = df['has_secondary_use_health_post'].astype('bool')
df['has_secondary_use_gov_office'] = df['has_secondary_use_gov_office'].astype('bool')
df['has_secondary_use_use_police'] = df['has_secondary_use_use_police'].astype('bool')
df['has_secondary_use_other'] = df['has_secondary_use_other'].astype('bool')

df['has_superstructure_adobe_mud'] = df['has_superstructure_adobe_mud'].astype('bool')
df['has_superstructure_mud_mortar_stone'] = df['has_superstructure_mud_mortar_stone'].astype('bool')
df['has_superstructure_stone_flag'] = df['has_superstructure_stone_flag'].astype('bool')
df['has_superstructure_cement_mortar_stone'] = df['has_superstructure_cement_mortar_stone'].astype('bool')
df['has_superstructure_mud_mortar_brick'] = df['has_superstructure_mud_mortar_brick'].astype('bool')

df['has_superstructure_cement_mortar_brick'] = df['has_superstructure_cement_mortar_brick'].astype('bool')
df['has_superstructure_timber'] = df['has_superstructure_timber'].astype('bool')
df['has_superstructure_bamboo'] = df['has_superstructure_bamboo'].astype('bool')
df['has_superstructure_rc_non_engineered'] = df['has_superstructure_rc_non_engineered'].astype('bool')
df['has_superstructure_rc_engineered'] = df['has_superstructure_rc_engineered'].astype('bool')
df['has_superstructure_other'] = df['has_superstructure_other'].astype('bool')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 39 columns):
building_id                               260601 non-null int64
geo_level_1_id                            260601 non-null int64
geo_level_2_id                            260601 non-null int64
geo_level_3_id                            260601 non-null int64
count_floors_pre_eq                       260601 non-null int64
age                                       260601 non-null int64
area_percentage                           260601 non-null int64
height_percentage                         260601 non-null int64
land_surface_condition                    260601 non-null category
foundation_type                           260601 non-null category
roof_type                                 260601 non-null category
ground_floor_type                         260601 non-null category
other_floor_type                          260601 non-null category
position                                  260601 non-null category
plan_configuration                        260601 non-null category
has_superstructure_adobe_mud              260601 non-null bool
has_superstructure_mud_mortar_stone       260601 non-null bool
has_superstructure_stone_flag             260601 non-null bool
has_superstructure_cement_mortar_stone    260601 non-null bool
has_superstructure_mud_mortar_brick       260601 non-null bool
has_superstructure_cement_mortar_brick    260601 non-null bool
has_superstructure_timber                 260601 non-null bool
has_superstructure_bamboo                 260601 non-null bool
has_superstructure_rc_non_engineered      260601 non-null bool
has_superstructure_rc_engineered          260601 non-null bool
has_superstructure_other                  260601 non-null bool
legal_ownership_status                    260601 non-null category
count_families                            260601 non-null int64
has_secondary_use                         260601 non-null bool
has_secondary_use_agriculture             260601 non-null bool
has_secondary_use_hotel                   260601 non-null bool
has_secondary_use_rental                  260601 non-null bool
has_secondary_use_institution             260601 non-null bool
has_secondary_use_school                  260601 non-null bool
has_secondary_use_industry                260601 non-null bool
has_secondary_use_health_post             260601 non-null bool
has_secondary_use_gov_office              260601 non-null bool
has_secondary_use_use_police              260601 non-null bool
has_secondary_use_other                   260601 non-null bool
dtypes: bool(22), category(8), int64(9)
memory usage: 25.4 MB

In [13]:
df = df.merge(df2)
df.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,damage_grade
0,802906,6,487,12198,2,30,6,5,t,r,...,False,False,False,False,False,False,False,False,False,3
1,28830,8,900,2812,2,10,8,7,o,r,...,False,False,False,False,False,False,False,False,False,2
2,94947,21,363,8973,2,10,5,5,t,r,...,False,False,False,False,False,False,False,False,False,3
3,590882,22,418,10694,2,10,6,5,t,r,...,False,False,False,False,False,False,False,False,False,2
4,201944,11,131,1488,3,30,8,9,t,r,...,False,False,False,False,False,False,False,False,False,3

In [14]:
df.to_csv('dataset_v1')