In [15]:
%matplotlib inline

from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df1 = pd.read_csv('dataset_v1').set_index('building_id')
df2 = pd.read_csv('dataset_v2').drop(columns=['Unnamed: 0']).set_index('building_id')
df3 = pd.read_csv('dataset_v3').set_index('building_id')

In [17]:
df2.head()

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,position_C0,position_C1,position_C2,plan_configuration_C0,plan_configuration_C1,plan_configuration_C2,plan_configuration_C3,legal_ownership_status_C0,legal_ownership_status_C1,legal_ownership_status_C2
building_id,,,,,,,,,,,,,,,,,,,,,
802906,6,487,12198,2,30,6,5,True,True,False,...,1,0,0,1,0,0,0,1,0,0
28830,8,900,2812,2,10,8,7,False,True,False,...,0,1,0,1,0,0,0,1,0,0
94947,21,363,8973,2,10,5,5,False,True,False,...,1,0,0,1,0,0,0,1,0,0
590882,22,418,10694,2,10,6,5,False,True,False,...,0,1,0,1,0,0,0,1,0,0
201944,11,131,1488,3,30,8,9,True,False,False,...,0,1,0,1,0,0,0,1,0,0

In [18]:
# En esta version del dataset incluyo las siguientes columnas del df1,
# mas las columnas encodeadas del df2 (binary encoding).
# Descarto las columnas con informacion legal (usos secundarios y legal_status encodeado)
# NO incluyo damage_grade (esta en el csv 'train_labels.csv')

selected_features = [
    'geo_level_1_id',
    'geo_level_2_id',
    'geo_level_3_id',
    'age',
    'area_percentage',
    'height_percentage',
    'has_superstructure_adobe_mud',
    'has_superstructure_mud_mortar_stone',
    'has_superstructure_stone_flag',
    'has_superstructure_cement_mortar_stone',
    'has_superstructure_mud_mortar_brick',
    'has_superstructure_cement_mortar_brick',
    'has_superstructure_timber',
    'has_superstructure_bamboo',
    'has_superstructure_rc_non_engineered',
    'has_superstructure_rc_engineered'
]

df2_selected_features = [
    'land_surface_condition_C0',
    'land_surface_condition_C1',
    'foundation_type_C0',
    'foundation_type_C1',
    'foundation_type_C2',
    'ground_floor_type_C0',
    'ground_floor_type_C1',
    'ground_floor_type_C2',
    'other_floor_type_C0',
    'other_floor_type_C1',
    'other_floor_type_C2',
    'position_C0',
    'position_C1',
    'position_C2',
    'plan_configuration_C0',
    'plan_configuration_C1',
    'plan_configuration_C2',
    'plan_configuration_C3'
]

In [19]:
df2_subset = df2.loc[: , df2_selected_features]
df4 = df1.join(df2_subset).loc[:, selected_features + df2_selected_features]
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 802906 to 747594
Data columns (total 34 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   geo_level_1_id                          260601 non-null  int64
 1   geo_level_2_id                          260601 non-null  int64
 2   geo_level_3_id                          260601 non-null  int64
 3   age                                     260601 non-null  int64
 4   area_percentage                         260601 non-null  int64
 5   height_percentage                       260601 non-null  int64
 6   has_superstructure_adobe_mud            260601 non-null  bool
 7   has_superstructure_mud_mortar_stone     260601 non-null  bool
 8   has_superstructure_stone_flag           260601 non-null  bool
 9   has_superstructure_cement_mortar_stone  260601 non-null  bool
 10  has_superstructure_mud_mortar_brick     260601 non-null  bool
 11  has_superstructure_cement_mortar_brick  260601 non-null  bool
 12  has_superstructure_timber               260601 non-null  bool
 13  has_superstructure_bamboo               260601 non-null  bool
 14  has_superstructure_rc_non_engineered    260601 non-null  bool
 15  has_superstructure_rc_engineered        260601 non-null  bool
 16  land_surface_condition_C0               260601 non-null  int64
 17  land_surface_condition_C1               260601 non-null  int64
 18  foundation_type_C0                      260601 non-null  int64
 19  foundation_type_C1                      260601 non-null  int64
 20  foundation_type_C2                      260601 non-null  int64
 21  ground_floor_type_C0                    260601 non-null  int64
 22  ground_floor_type_C1                    260601 non-null  int64
 23  ground_floor_type_C2                    260601 non-null  int64
 24  other_floor_type_C0                     260601 non-null  int64
 25  other_floor_type_C1                     260601 non-null  int64
 26  other_floor_type_C2                     260601 non-null  int64
 27  position_C0                             260601 non-null  int64
 28  position_C1                             260601 non-null  int64
 29  position_C2                             260601 non-null  int64
 30  plan_configuration_C0                   260601 non-null  int64
 31  plan_configuration_C1                   260601 non-null  int64
 32  plan_configuration_C2                   260601 non-null  int64
 33  plan_configuration_C3                   260601 non-null  int64
dtypes: bool(10), int64(24)
memory usage: 62.2 MB

In [20]:
df4.to_csv('dataset_v4.csv')